export const PATHS = {
  HOME: "/",
  OFFERS: "/offers",
  ABOUT_US: "/about-us",
  PROFILE: "/profile",
  DETAIL: "/detail/:id",
  SESSION: "/session",
  SEATS: "/seats",
  CONFIRMATION: "/confirmation",
  MY_TICKETS: "/my-tickets",
  ERROR: "*",
  ADMIN: "/admin",
  ADMIN_FUNCTION_LIST: "/admin/functions",
  ADMIN_NEW_FUNCTION: "/admin/functions/new",
  ADMIN_FILM_LIST: "/admin/films",
  ADMIN_NEW_FILM: "/admin/films/new",
  LOGIN: "/login",
};
